### ISSUE TITLE
Create plotting tools for route planning work

### ISSUE THREAD

**Issue by DaniJonesOcean** [so-wise/antarctic_sea_ice_extent#4]
Probably cartopy. Take output from Java (from Maria Fox) then plot in either python or Matlab. 

Input:
- Mesh: cell coordinates
- Vehicle paths: vectors of coordinates
- Bathymetry (need to select)
- Sea ice (daily one or the monthly one, latter used for planning)
- Average currents 
- Refined mesh along the coast

Output: 
- Plots!

**Comment by DanJonesOcean** [comment]
This should probably be a separate repository.
